### PR TITLE
new icon

### PR DESCRIPTION
**Pull request by T8RIN**
Suggestion for the #50

### CODE REVIEW

**Comment by T8RIN** [comment]
image
image

**Review by IacobIonut01 — CHANGES_REQUESTED** [review]
Remove the added whitespace in themes.xml and make the 'ic_launcher_background' back to White

**Review by IacobIonut01 — APPROVED** [review]

**Comment by T8RIN** [comment]
Done

**Comment by IacobIonut01** [comment]
@T8RIN could you email me or telegram me at @iacobionut01 the svg files of the icons?

**Pull request merged**
