### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
This PR adds the metadata for your app to the repo, using Fastlane structures – giving it into your hands how your app is presented e.g. in my repo. Be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) to build on this to e.g. add screenshots, a featureGraphic, maybe even per-release changelogs. Your updates to these structures would be pulled along with future releases then.

If there are any questions, feel free to ask!

### CODE REVIEW

**Comment by IacobIonut01** [comment]
Thanks! I'll update the structure, desc and screenshots later on

**Comment by IzzySoft** [comment]
Thanks! Please let me know when you did, so I can cross-check what I might need to adjust on my end.

**Comment by IzzySoft** [comment]
Changelog must be plain ASCII, sorry… I've just updated my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) to make this clearer.

**Comment by IacobIonut01** [comment]
Alright, updated the changelog

**Comment by IzzySoft** [comment]
Looks good! Enabled on my end, and just downloaded the current one manually (as the corresponding release is already here). Should show up with the next sync then. Thanks!

**Pull request merged**
